name: build-test-grpc-client

on:
  push:
    paths:
      - 'packages/grpc-client/**'
      - '.github/workflows/build-test-grpc-client.yaml'
  pull_request:
    paths:
      - 'packages/grpc-client/**'
      - '.github/workflows/build-test-grpc-client.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter grpc-client... install

      - name: Build
        run: pnpm -r --filter grpc-client... build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1

      - name: Install Dependencies
        run: pnpm -r --filter grpc-client... install

      - name: Build
        run: pnpm -r --filter grpc-client... build

      - name: Test
        run: pnpm -r --filter grpc-client test
