name: build-test-facade

on:
  push:
    paths:
      - 'packages/facade/**'
      - '.github/workflows/build-test-facade.yaml'
  pull_request:
    paths:
      - 'packages/facade/**'
      - '.github/workflows/build-test-facade.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Install Dependencies
        run: pnpm -r --filter facade... install

      - name: Build
        run: pnpm -r --filter facade... build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1
        with:
          backing-only: false
          shutdown: facade-srv

      - name: Install Dependencies
        run: pnpm -r --filter facade... install

      - name: Build
        run: pnpm -r --filter facade... build

      - name: Test
        run: pnpm -r --filter facade test
