name: build-test-gql-bot

on:
  push:
    paths:
      - 'packages/gql-bot/**'
      - '.github/workflows/build-test-gql-bot.yaml'
  pull_request:
    paths:
      - 'packages/gql-bot/**'
      - '.github/workflows/build-test-gql-bot.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter gql-bot... install

      - name: Build
        run: pnpm -r --filter gql-bot... build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter gql-bot... install

      - name: Build
        run: pnpm -r --filter gql-bot... build

      - name: Test
        run: pnpm -r --filter gql-bot test && pnpm -r --filter gql-bot lcov-report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/gql-bot
          path-to-lcov: ./packages/gql-bot/coverage/lcov.info
