name: build-test-acs-client

on:
  push:
    paths:
      - 'packages/acs-client/**'
      - '.github/workflows/build-test-acs-client.yaml'
  pull_request:
    paths:
      - 'packages/acs-client/**'
      - '.github/workflows/build-test-acs-client.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter acs-client... install

      - name: Build
        run: pnpm -r --filter acs-client... build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1
        with:
          backing-only: true

      - name: Install Dependencies
        run: pnpm -r --filter acs-client... install

      - name: Build
        run: pnpm -r --filter acs-client... build

      - name: Test
        run: pnpm -r --filter acs-client test && pnpm -r --filter acs-client lcov-report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/acs-client
          path-to-lcov: ./packages/acs-client/coverage/lcov.info
