name: build-test-acs-client

on:
  push:
    paths:
      - 'packages/acs-client/**'
      - '.github/workflows/build-test-acs-client.yaml'
  pull_request:
    paths:
      - 'packages/acs-client/**'
      - '.github/workflows/build-test-acs-client.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'

      - name: Upgrade npm
        run: npm i -g npm

      - name: Install Dependencies
        run: npm ci && npm run install:ci -- --scope="@restorecommerce/acs-client" --include-filtered-dependencies

      - name: Build
        run: npm run build -- --scope="@restorecommerce/acs-client" --include-filtered-dependencies

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'

      - name: Upgrade npm
        run: npm i -g npm

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1
        with:
          backing-only: true

      - name: Install Dependencies
        run: npm ci && npm run install:ci -- --scope="@restorecommerce/acs-client" --include-filtered-dependencies

      - name: Build
        run: npm run build -- --scope="@restorecommerce/acs-client" --include-filtered-dependencies

      - name: Test
        run: npm run test && npm run lcov-report
        working-directory: ./packages/acs-client

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/acs-client
