name: build-test-cart

on:
  push:
    paths:
      - 'packages/cart/**'
      - '.github/workflows/build-test-cart.yaml'
  pull_request:
    paths:
      - 'packages/cart/**'
      - '.github/workflows/build-test-cart.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Install Dependencies
        run: pnpm -r --filter cart... install

      - name: Build
        run: pnpm -r --filter cart... build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1

      - name: Install Dependencies
        run: pnpm -r --filter cart... install

      - name: Build
        run: pnpm -r --filter cart... build

      - name: Test
        run: pnpm -r --filter cart test
