name: build-test-logger

on:
  push:
    paths:
      - 'packages/logger/**'
      - '.github/workflows/build-test-logger.yaml'
  pull_request:
    paths:
      - 'packages/logger/**'
      - '.github/workflows/build-test-logger.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter logger... install

      - name: Build
        run: pnpm -r --filter logger... build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Setup System
        uses: restorecommerce/setup-system-action@v1
        with:
          backing-only: true

      - name: Install Dependencies
        run: pnpm -r --filter logger... install

      - name: Build
        run: pnpm -r --filter logger... build

      - name: Test
        run: pnpm -r --filter logger test

      - name: View logged messages
        run: curl "localhost:9200/logs-app-default/_search?size=100" | jq
