name: build-test-oidc-id-srv-integration

on:
  push:
    paths:
      - 'packages/oidc-id-srv-integration/**'
      - '.github/workflows/build-test-oidc-srv-integration.yaml'
  pull_request:
    paths:
      - 'packages/oidc-id-srv-integration/**'
      - '.github/workflows/build-test-oidc-srv-integration.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter oidc-id-srv-integration... install

      - name: Build
        run: pnpm -r --filter oidc-id-srv-integration... build

  test:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter oidc-id-srv-integration... install

      - name: Build
        run: pnpm -r --filter oidc-id-srv-integration... build

      - name: Test
        run: pnpm -r --filter oidc-id-srv-integration test
