name: build-test-rc-grpc-clients

on:
  push:
    paths:
      - 'packages/rc-grpc-clients/**'
      - '.github/workflows/build-test-rc-grpc-clients.yaml'
  pull_request:
    paths:
      - 'packages/rc-grpc-clients/**'
      - '.github/workflows/build-test-rc-grpc-clients.yaml'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter rc-grpc-clients... install

      - name: Build
        run: pnpm -r --filter rc-grpc-clients... build
