name: test-mailer

on:
  push:
    paths:
      - 'packages/mailer/**'
      - '.github/workflows/test-mailer.yaml'
  pull_request:
    paths:
      - 'packages/mailer/**'
      - '.github/workflows/test-mailer.yaml'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Install Dependencies
        run: pnpm -r --filter mailer... install

      - name: Test
        run: pnpm -r --filter mailer test && pnpm -r --filter mailer lcov-report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/mailer
          path-to-lcov: ./packages/mailer/coverage/lcov.info
