name: test-handlebars-helperized

on:
  push:
    paths:
      - 'packages/handlebars-helperized/**'
      - '.github/workflows/test-handlebars-helperized.yaml'
  pull_request:
    paths:
      - 'packages/handlebars-helperized/**'
      - '.github/workflows/test-handlebars-helperized.yaml'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Install Dependencies
        run: pnpm -r --filter handlebars-helperized... install

      - name: Test
        run: pnpm -r --filter handlebars-helperized test && pnpm -r --filter handlebars-helperized lcov-report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/handlebars-helperized
          path-to-lcov: ./packages/handlebars-helperized/coverage/lcov.info
