name: test-koa-req-res-logger

on:
  push:
    paths:
      - 'packages/koa-req-res-logger/**'
      - '.github/workflows/test-koa-req-res-logger.yaml'
  pull_request:
    paths:
      - 'packages/koa-req-res-logger/**'
      - '.github/workflows/test-koa-req-res-logger.yaml'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0

      - name: Install Dependencies
        run: pnpm -r --filter koa-req-res-logger... install

      - name: Test
        run: pnpm -r --filter koa-req-res-logger test && pnpm -r --filter koa-req-res-logger lcov-report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/koa-req-res-logger
          path-to-lcov: ./packages/koa-req-res-logger/coverage/lcov.info
