name: test-mailer

on:
  push:
    paths:
      - 'packages/mailer/**'
      - '.github/workflows/test-mailer.yaml'
  pull_request:
    paths:
      - 'packages/mailer/**'
      - '.github/workflows/test-mailer.yaml'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'

      - name: Upgrade npm
        run: npm i -g npm

      - name: Install Dependencies
        run: npm ci && npm run install:ci -- --scope="@restorecommerce/mailer" --include-filtered-dependencies

      - name: Test
        run: npm run test
        working-directory: ./packages/mailer

      - name: Coverage
        run: npm run coveralls
        working-directory: ./packages/cluster-service
