name: test-koa-req-res-logger

on:
  push:
    paths:
      - 'packages/koa-req-res-logger/**'
      - '.github/workflows/test-koa-req-res-logger.yaml'
  pull_request:
    paths:
      - 'packages/koa-req-res-logger/**'
      - '.github/workflows/test-koa-req-res-logger.yaml'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'

      - name: Upgrade npm
        run: npm i -g npm

      - name: Install Dependencies
        run: npm ci && npm run install:ci -- --scope="@restorecommerce/koa-req-res-logger" --include-filtered-dependencies

      - name: Test
        run: npm run test
        working-directory: ./packages/koa-req-res-logger

      - name: Coverage
        run: npm run coveralls
        working-directory: ./packages/mailer
