name: test-cluster-service

on:
  push:
    paths:
      - 'packages/cluster-service/**'
      - '.github/workflows/test-cluster-service.yaml'
  pull_request:
    paths:
      - 'packages/cluster-service/**'
      - '.github/workflows/test-cluster-service.yaml'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.15'

      - name: Install Dependencies
        run: npm ci && npm run install:ci -- --scope="@restorecommerce/cluster-service" --include-filtered-dependencies

      - name: Test
        run: npm run test
        working-directory: ./packages/cluster-service

      - name: Coverage
        run: npm run coveralls
        working-directory: ./packages/cluster-service
