name: test-cluster-service

on:
  push:
    paths:
      - 'packages/cluster-service/**'
      - '.github/workflows/test-cluster-service.yaml'
  pull_request:
    paths:
      - 'packages/cluster-service/**'
      - '.github/workflows/test-cluster-service.yaml'

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Install Dependencies
        run: pnpm -r --filter cluster-service... install

      - name: Test
        run: pnpm -r --filter cluster-service test && pnpm -r --filter cluster-service lcov-report

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-path: packages/cluster-service
          path-to-lcov: ./packages/cluster-service/coverage/lcov.info
